//
//  EratosfenConfigurator.swift
//  RPEratosfen
//
//  Created by Юрий on 27.05.17.
//  Copyright (c) 2017 Юрий. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension EratosfenInteractor: EratosfenViewControllerOutput, EratosfenRouterDataSource, EratosfenRouterDataDestination {
}

extension EratosfenPresenter: EratosfenInteractorOutput {
}

class EratosfenConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = EratosfenConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: EratosfenViewController) {
        
        let presenter = EratosfenPresenter()
        presenter.output = viewController
        
        let interactor = EratosfenInteractor()
        interactor.output = presenter
        
        let router = EratosfenRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
