//
//  EratosfenViewController.swift
//  RPEratosfen
//
//  Created by Юрий on 27.05.17.
//  Copyright (c) 2017 Юрий. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol EratosfenViewControllerInput {
    func displaySumPrimes(sumPrimes: UInt)
    func displayPrimes(primes: String)
}

protocol EratosfenViewControllerOutput {
    func eratosfen(number: UInt)
}

class EratosfenViewController: UIViewController, EratosfenViewControllerInput, UITextFieldDelegate {
    
    var output: EratosfenViewControllerOutput?
    var router: EratosfenRouter?
    
    @IBOutlet weak var numberTextField: UITextField!
    @IBOutlet weak var primeNumbersView: UITextView!
    @IBOutlet weak var sumPrimesTextField: UITextField!
    @IBOutlet weak var button: UIButton!
    @IBOutlet weak var loading: UIActivityIndicatorView!
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        EratosfenConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        primeNumbersView.layer.borderWidth = 1.0
        primeNumbersView.layer.borderColor = UIColor.lightGray.withAlphaComponent(0.3).cgColor
    }
    
    // MARK: IBAction
    
    @IBAction func calculatePrimeNumbers() {
        numberTextField.resignFirstResponder()
        button.isEnabled = false
        loading.startAnimating()
        
        let number = UInt(numberTextField.text!)
        if (number != nil) {
            if number! >= 2 {
                primeNumbersView.text = ""
                sumPrimesTextField.text = ""
                
                output?.eratosfen(number: number!)
            } else {
                let alert = UIAlertController.init(title: nil, message: "Введите число больше 2", preferredStyle: .alert)
                alert.addAction(UIAlertAction.init(title: "Ok", style: .cancel, handler: nil))
                self.present(alert, animated: true, completion: nil)
            }
        } else {
            let alert = UIAlertController.init(title: nil, message: "Введите число", preferredStyle: .alert)
            alert.addAction(UIAlertAction.init(title: "Ok", style: .cancel, handler: nil))
            self.present(alert, animated: true, completion: nil)
        }
    }
    
    // MARK: Display logic
    
    internal func displaySumPrimes(sumPrimes: UInt) {
        loading.stopAnimating()
        button.isEnabled = true
        sumPrimesTextField.text = String(sumPrimes)
    }
    
    internal func displayPrimes(primes: String) {
        primeNumbersView.text = primes
    }
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension EratosfenViewController: EratosfenPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(for: segue)
    }
}
