//
//  EratosfenPresenter.swift
//  RPEratosfen
//
//  Created by Юрий on 27.05.17.
//  Copyright (c) 2017 Юрий. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol EratosfenPresenterInput {
    func presentSumPrimes(primes: [UInt])
    func presentPrimes(primes: [UInt])
}

protocol EratosfenPresenterOutput: class {
    func displaySumPrimes(sumPrimes: UInt)
    func displayPrimes(primes: String)
}

class EratosfenPresenter: EratosfenPresenterInput {

    weak var output: EratosfenPresenterOutput?
    
    // MARK: Presentation logic
    
    internal func presentPrimes(primes: [UInt]) {
        var primesString = ""
        for prime in primes {
            primesString += String(prime) + "\n"
        }
        output?.displayPrimes(primes: primesString)
    }
    
    internal func presentSumPrimes(primes: [UInt]) {
        var sumPrimes: UInt = 0
        for prime in primes {
            if (UInt.max - prime > sumPrimes) {
                sumPrimes += prime
            }
        }
        output?.displaySumPrimes(sumPrimes: sumPrimes)
    }
}
