//
//  EratosfenModels.swift
//  RPEratosfen
//
//  Created by Юрий on 27.05.17.
//  Copyright (c) 2017 Юрий. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
//
//  Type "usecase" for some magic!

struct EratosfenScene {
    
}
