//
//  EratosfenRouter.swift
//  RPEratosfen
//
//  Created by Юрий on 27.05.17.
//  Copyright (c) 2017 Юрий. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol EratosfenRouterInput {
    
}

protocol EratosfenRouterDataSource: class {
    
}

protocol EratosfenRouterDataDestination: class {
    
}

class EratosfenRouter: EratosfenRouterInput {
    
    weak var viewController: EratosfenViewController!
    weak private var dataSource: EratosfenRouterDataSource!
    weak var dataDestination: EratosfenRouterDataDestination!
    
    init(viewController: EratosfenViewController, dataSource: EratosfenRouterDataSource, dataDestination: EratosfenRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
